#!/usr/bin/env python3

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group('Options for rqt_marine_control plugin')
    group.add_argument('topic', nargs='?', help='ControlSet state topic to display')


main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='rqt_marine_control/MarineControl',
    plugin_argument_provider=add_arguments))
