#!/usr/bin/env python

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group('Options for rqt_sonar_waterfall plugin')
    group.add_argument('port_topic', nargs='?', help='RawSonarImage port topic')
    group.add_argument('starboard_topic', nargs='?', help='RawSonarImage starboard topic')
    group.add_argument('control_topic', nargs='?', help='RadarControlSet control-state topic')


main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='rqt_sonar_waterfall/SonarWaterfall',
    plugin_argument_provider=add_arguments))
